# Client

client

proto           tcp
dev             tun
remote          vpn2.oster.com.ua 10111

ca              client/ca.crt
cert            client/VladVons.crt
key             client/VladVons.key

cipher AES-256-CBC
keepalive       10 120
nobind

persist-key
persist-tun

verb            3
mute            10
