# 2024-09-22
# VladVons

[Interface]
PrivateKey = EA7zRk9cr8Uf8QVjsY4V7LoBO/AUCuz/bPwTJI+UFFc=
Address = 10.71.2.2/32

[Peer]
PublicKey = 04rqkq67vchHUYfTGJUIiBlaZl3jnsBay8BZLqUNhGA=
Endpoint = vpn2.oster.com.ua:10721
AllowedIPs = 10.71.2.0/24

#-- Nat
PersistentKeepalive = 25
