#--- VladVons
# linux client config file.

client

proto           udp
dev             tun_vpn10102
remote          vpn2.oster.com.ua 10102

ca              OlegVons/ca.crt
cert            OlegVons/OlegVons.crt
key             OlegVons/OlegVons.key

keepalive       10 120
nobind

user            nobody
group           nogroup

persist-key
persist-tun

verb            3
mute            10
